### PR TITLE
Update to Shiprekt+v11, add maps, add README.md

### PR DESCRIPTION
**Pull request by rubenwardy**
v11.2 should then be added as another commit - but I don't have it.

https://github.com/rubenwardy/ShiprektPlus/blob/master/README.md

# ShipRekt+

Version v11

License: WTFPL or CC0. (From discussion with author, this is what came across)

[Shiprekt+ on KAG Resources](https://forum.kag2d.com/resources/shiprekt-plus.234/)

# Installation

* Download and extract this zip to KAG/Mods/Shiprekt+v11
* The README.md should now be at KAG/Mods/Shiprekt+v11/README.md
* Add `Shiprekt+v11` to mods.cfg
* Set `sv_gamemode` to `TDM` in autoconfig.cfg
* Run a server: ./KAGdedi autostart Scripts/server_autostart.as autoconfig autoconfig.cfg

# Changes

## Features

* Ship ownership and team captains.
* Selectable blocks bought with..
* Booty($) that can be gathered through the map or gained through combat.
* Mounted machineguns and hand pistols.
* Couplings managing and docking.
* Team ladderboard.
* Sudden Death mode.
* Mothership explosions.

# Bugfixes

* Misplaced blocks while on a moving ship.
* Slowly lagging behind on a moving ship (client side).

# Special thanks

* MM and Geti for creating the original Shiprekt.
* Chrispin - for his contributions to weapons
* Skinney - for his sprites
* AsuMagic - hosting the gamemode on its early stages

### CODE REVIEW

**Comment by rubenwardy** [comment]
This is sad

**Comment by Chrispin** [comment]
YOU'RE SAD, RUBENWARDY
btw you know what happened to Strathos? I have v11.41 up in a server most times of the day

**Comment by rubenwardy** [comment]
Errr, what?
This is sad because it's been ignored for 8 months. There really should be an upstream repo with the latest version somewhere.

**Comment by rubenwardy** [comment]
Bump. Is there a main repo yet?

**Comment by terracraft321** [comment]
Could you update this for the current build?

**Pull request closed without merging**
